//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameworkLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public Nullable<int> Student { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<short> Exam1 { get; set; }
        public Nullable<short> Exam2 { get; set; }
        public Nullable<short> Exam3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Lesson Lesson1 { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
